name: 'Build Jekyll for GitHub Pages Securely'
description: 'A simple GitHub Action for producing pinned Jekyll release artifacts'
author: 'Github + Shant Tchatalbachian'
runs:
  using: docker
  image: docker://ghcr.io/actions/jekyll-build-pages@sha256:6791ebfd912185ed59bfb5fb102664fa872496b79f87ff8b9cfba292a7345041 #v1.0.13
branding:
  icon: aperture
  color: purple
inputs:
  source:
    description: 'Directory where the source files reside.'
    required: false
    default: './'
  destination:
    description: 'Output directory of the build. Although it can be nested inside the source, it cannot be the same as the source directory.'
    required: true
    default: './_site'
  future:
    description: 'Publishes posts with a future date. When set to true, the build is made with the --future option which overrides the future option that may be set in a Jekyll configuration file.'
    required: false
    default: false
  build_revision:
    description: 'The SHA-1 of the git commit for which the build is running. Default to GITHUB_SHA.'
    required: false
    default: ${{github.sha}}
  verbose:
    description: 'Verbose output'
    required: false
    default: true
  token:
    description: 'GitHub token'
    required: true
    default: ${{github.token}}
