name: Fetch and Validate PKI
run-name: Fetch and Validate PKI
on:
  workflow_call:
    secrets:
      DOCKER:
        description: 'A secret passed from the caller workflow'
        required: true
permissions: {}
concurrency:
  group: release
  cancel-in-progress: true
jobs:
  fetch-validate:
    permissions:
      id-token: write
      contents: write
    environment:
      name: release
    runs-on: ubuntu-latest
    container:
      credentials:
        username: 0mniteck42
        password: ${{secrets.DOCKER}}
      image: docker://dhi.io/debian-base@sha256:9415967aa0ed8adea8b5c048994259d1982026dca143d0303c7bbe0e11ed67d3 # v2026.03.14 trixie-debian13-dev dhi/debian-base
    steps:
      - name: Apt Install
        run: apt-get -qq update > /dev/null && apt-get install curl dnsutils git -qq --no-install-recommends > /dev/null && which curl dig git || exit 1
      - name: Git Config
        run: git config --global --add safe.directory /__w/.pki/.pki && git config --global init.defaultBranch main
      - name: Checkout v6
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Git Fetch
        run: git fetch && git pull origin main && echo Fetched
      - name: Validate PKI
        shell: bash
        run: |
          state="$(curl --version | grep curl)\n$(openssl --version)\n$(dig -v)"
          enforce_doh="--disable --doh-cert-status --doh-url https://one.one.one.one/dns-query --resolve one.one.one.one:443:1.1.1.1"
          common_tls="--tlsv1.3 --proto -all,+https --remove-on-error --no-insecure -s"
          rm -f index.state; touch index.version index.state
          echo -n $(($(cat index.version) + 1)) > index.version
          echo -e $state > index.state; echo -e $state
          
          validate.pki() { # $1 = domain/FQDN/IDN
            curl $enforce_doh --pinnedpubkey "sha256//$(cat registry/$1.pubkey | cut -d' ' -f1)" \
            $common_tls https://$1 > /dev/null || return 1
            echo -e "\nSuccessfully fetched and checked validity for $1"
            if [[ -f "registry/$1.etag" ]]; then echo -en " --> +etag"; fi;
            if [[ -f "registry/$1.pq" ]]; then echo -en " --> +post_quantum"; fi;
            if [[ -f "registry/$1.dnssec" ]]; then echo -en " --> +dnssec"; fi;
            echo -e "\n$e:\nSuccessfully fetched and checked validity for $1" >> index.state
            if [[ -f "registry/$1.etag" ]]; then echo -en " --> +etag" >> index.state; fi;
            if [[ -f "registry/$1.pq" ]]; then echo -en " --> +post_quantum" >> index.state; fi;
            if [[ -f "registry/$1.dnssec" ]]; then echo -en " --> +dnssec" >> index.state; fi; return 0
          }
          
          fetch.pki() { # $1 = domain/FQDN/IDN
            pushd registry > /dev/null
              if [[ -s "$1.etag" ]]; then echo $(cat $1.etag | cut -d' ' -f1) > $1.etag; fi;
              curl $enforce_doh $common_tls --etag-save $1.etag --etag-compare $1.etag -w %{certs} https://$1 | \
              sed --sandbox -n "/-----BEGIN/,/-----END/p;/-----END/q" > $1.pem && \
              openssl x509 -in $1.pem -pubkey -noout > $1.pubkey.pem && openssl x509 -in $1.pem -enddate -noout | \
              tr '\n' '=' > $1.exp && echo -en $e >> $1.exp && \
              openssl asn1parse -noout -inform pem -in $1.pubkey.pem -out $1.pubkey.der && \
              openssl dgst -sha256 -binary $1.pubkey.der | openssl base64 | tr '\n' ' ' > $1.pubkey && \
              echo -en $e >> $1.pubkey && declare -g -- SUCCESS+=:local.fetch.pki:$1 || exit 1
              rm -f *.pem *.der $1.pq $1.dnssec
              if [[ ! -s "$1.etag" ]]; then rm -f $1.etag; else echo $(cat $1.etag | tr '\n' ' ') > $1.etag; echo -en ' '$e >> $1.etag; fi;
              PQC=$(cat <(curl $enforce_doh $common_tls -o /dev/null -v https://$1 2>&1 | grep -e 'SSL certificate verify ok' -e 'SSL connection using' | sed 's/\* /\\n/g' | sed 's/\\nS/S/g' | sed 's/ SSL/SSL/g'))
              echo -en $PQC | grep -e MLKEM -e MLDSA -e SLHDSA > /dev/null && touch $1.pq && echo -en $PQC > $1.pq || printf ''
              DIG=$(cat <(dig -r +https +do +domain=$1 +yaml @one.one.one.one -q $1 -t SIG | tr '\n' '^' ))
              echo -en $DIG | tr '^' '\n' | grep 'qr rd ra ad' > /dev/null && touch $1.dnssec && echo -en $DIG | tr '^' '\n' > $1.dnssec || printf ''
            popd > /dev/null
            validate.pki $1 || exit 1
          }
          
          check.csv() { # $1 = domain/FQDN/IDN
            date=$(date +%s)
            dater=$(date -d "$(cat registry/$1.exp | cut -d'=' -f2)" +%s)
            if [[ "$dater" -le "$date" ]]; then
              echo "$1.pubkey expired"
              fetch.pki $1 || exit 1
            else
              validate.pki $1 || fetch.pki $1 || exit 1; fi;
          }
          
          check.pki() { # $1 = domain/FQDN/IDN
            if [[ -f "registry/$1.pubkey" ]]; then
              check.csv $1 || exit 1
            else
              fetch.pki $1 || exit 1
            fi
          }
          
          check.index() {
            unset e; e=1;
            for i in $(cat index.csv | tr ',' '\n' | cat); do
              declare -g -- e=$((e + 1))
              check.pki $i || exit 1
            done
          }

          clean.registry() {
            rm -rf registry/*
          }
          
          pushd /__w/.pki/.pki > /dev/null
            clean.registry || exit 1
            check.index || exit 1
            git config user.name 'github-actions[bot]'
            git config user.email 'github-actions[bot]@users.noreply.github.com'
            git add -A && git commit -m "Index number $(cat index.version) - $(date '+on %m/%d/%y at %H:%M UTC')"
            git push origin HEAD:main
          popd > /dev/null && echo DONE
