name: Fetch and Validate PKI
run-name: Fetch and Validate PKI
on:
  workflow_call:
concurrency:
  group: release
  cancel-in-progress: true
jobs:
  fetch-validate:
    runs-on: ubuntu-latest
    environment:
      name: release
    steps:
      - name: Checkout v6
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Git fetch
        id: git_fetch
        run: git fetch && git pull origin main && echo Fetched
      - name: Validate PKI
        run: |
          touch index.ver
          index_number=$(($(cat index.ver) + 1))
          echo $index_number > index.ver
          enforce_doh="--disable --doh-cert-status --doh-url https://one.one.one.one/dns-query --resolve one.one.one.one:443:1.1.1.1"
          common_tls="--tlsv1.3 --proto -all,+https --remove-on-error --no-insecure -s"
          
          validate.pki() { # $1 = domain/FQDN/IDN
            curl $enforce_doh --pinnedpubkey "sha256//$(cat registry/$1.pubkey | cut -d' ' -f1)" \
            $common_tls https://$1 > /dev/null || return 1
            echo "Successfully fetched and checked validity for $1"
            if [[ -f "registry/$1.dnssec.valid" ]]; then
              cp registry/$1.dnssec registry/$1.dnssec.valid; echo " --> +dnssec"; fi;
            rm -f registry/$1.dnssec; return 0
          }
          
          fetch.pki() { # $1 = domain/FQDN/IDN
            pushd registry > /dev/null
              if [[ -s "$1.etag" ]]; then cat $1.etag | cut -d' ' -f1 > $1.etag; fi;
              curl $enforce_doh $common_tls --etag-save $1.etag --etag-compare $1.etag -w %{certs} https://$1 | sed --sandbox -n "/-----BEGIN/,/-----END/p;/-----END/q" > $1.pem && \
              openssl x509 -in $1.pem -pubkey -noout > $1.pubkey.pem && openssl x509 -in $1.pem -enddate -noout | tr '\n' '=' > $1.exp && \
              echo -en $e >> $1.exp && openssl asn1parse -noout -inform pem -in $1.pubkey.pem -out $1.pubkey.der && \
              openssl dgst -sha256 -binary $1.pubkey.der | openssl base64 | tr '\n' ' ' > $1.pubkey && echo -en $e >> $1.pubkey && \
              declare -g -- SUCCESS+=:local.fetch.pki:$1 || exit 1 && rm -f *.pem *.der $1.dnssec* && touch $1.dnssec
              if [[ ! -s "$1.etag" ]]; then rm -f $1.etag; else echo $(cat $1.etag | tr '\n' ' ') > $1.etag; echo -en ' '$e >> $1.etag; fi;
              dig -r +https +do +domain=$1 +yaml @one.one.one.one -q $1 -t SIG > $1.dnssec
              if [[ "$(cat $1.dnssec | grep -o 'qr rd ra ad')" == "qr rd ra ad" ]]; then
                touch $1.dnssec.valid; echo null > $1.dnssec.valid; fi;
            popd > /dev/null
            validate.pki $1 || exit 1
          }
          
          check.csv() { # $1 = domain/FQDN/IDN
            date=$(date +%s)
            dater=$(date -d "$(cat registry/$1.exp | cut -d'=' -f2)" +%s)
            if [[ "$dater" -le "$date" ]]; then
              echo "$1.pubkey expired"
              fetch.pki $1 || exit 1
            else
              validate.pki $1 || fetch.pki $1 || exit 1
            fi
          }
          
          check.pki() { # $1 = domain/FQDN/IDN
            if [[ -f "registry/$1.pubkey" ]]; then
              check.csv $1 || exit 1
            else
              fetch.pki $1 || exit 1
            fi
          }
          
          check.index() {
            unset e; e=1;
            for i in $(cat index.csv | tr ',' '\n' | cat); do
              declare -g -- e=$((e + 1))
              check.pki $i || exit 1
            done
          }

          clean.registry() {
            rm -rf registry/*
          }
          
          pushd ${{github.workspace}} > /dev/null
            clean.registry || exit 1
            check.index || exit 1
            git config user.name 'github-actions[bot]'
            git config user.email 'github-actions[bot]@users.noreply.github.com'
            git add -A && git commit -m "Index number $(cat index.ver) - $(date '+on %m/%d/%y at %H:%M UTC')"
            git push origin HEAD:main
          popd > /dev/null && echo DONE
