name: Deploy GH-Pages
run-name: Deploy GH-Pages
on:
  workflow_call:
permissions:
  id-token: write
  contents: read
concurrency:
  group: release
  cancel-in-progress: true
jobs:
  release-page:
    environment:
      name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout v6
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Git fetch
        run: git fetch && git pull origin main && echo Fetched
      - name: Set Config
        run: |
          cat >> ${{github.workspace}}/_config.yml << EOF
          theme: jekyll-theme-cayman
          show_downloads: false
          incremental: true
          google_analytics:
          lsi: true
          EOF
      - name: Setup Github Pages v6
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0
      - name: Build with Jekyll Securely
        uses: 0mniteck/.pki/.github/actions/jekyll/@32292725bd58fa67e8900db501acc3829dd4835e #v0.0.247
        with:
          destination: './_site'
          token: ${{github.token}}
      - name: Upload Pages Artifact v5
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          name: 'release'
          path: '_site/'
  push-page:
    permissions:
      pages: write
    environment:
      name: release
      url: ${{steps.deployment.outputs.page_url}}
    needs: release-page
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages v5
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
        with:
          artifact_name: 'release'
