name: Immutable Release
run-name: Immutable Release
on:
  workflow_call:
    outputs:
      URL: 
        value: ${{jobs.immutable-rel.outputs.URL}}
      SUMS:
        value: ${{jobs.immutable-rel.outputs.SUMS}}
      SIGNER:
        value: ${{jobs.immutable-rel.outputs.SIGNER}}
permissions: {}
concurrency:
  group: release
  cancel-in-progress: true
jobs:
  immutable-rel:
    permissions:
      id-token: write
      contents: write
      attestations: write
    environment:
      name: release
    outputs:
      URL: ${{steps.generate_attestation.outputs.attestation-url}}
      SUMS: ${{steps.add_assets.outputs.SUMS}}
      SIGNER: ${{steps.add_assets.outputs.SIGNER}}
    env:
      DIR: '/home/runner/work/_temp/attestations'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout v6
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Git Fetch
        id: git_fetch
        run: |
          git fetch && git pull origin ${{github.ref_name}} && echo Fetched
          echo "TAG=v0.0.$(cat index/index.version)" >> $GITHUB_OUTPUT
      - name: Clear Attestations
        id: clear_attestations
        run: |
          ATTEST=$(cat readme.md | sed -n '/attestations/,/]/p;//q' | cut -d'/' -f13 | cut -d')' -f1)
          DEL=$(curl -s -L -X DELETE -w "%{http_code}" \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{github.token}}" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            https://api.github.com/users/${{github.repository_owner}}/attestations/$ATTEST)
          if [[ "$DEL" == "404" ]]; then
            DIGESTS=$(sha512sum --tag .github/{actions/jekyll,workflows}/* registry/* index/index.* local.sh | cut -d'=' -f2 | sed 's/ /sha512:/g' | tr '\n' ' ')
            for DIGEST in $DIGESTS; do
            	curl -s -L -X DELETE \
            		-H "Accept: application/vnd.github+json" \
            		-H "Authorization: Bearer ${{github.token}}" \
            		-H "X-GitHub-Api-Version: 2026-03-10" \
            		https://api.github.com/users/${{github.repository_owner}}/attestations/digest/$DIGEST
              echo "Cleared Attestation for $DIGEST"
            done; fi; mkdir -p ${{env.DIR}}
          sha512sum .github/{actions/jekyll,workflows}/* registry/* index/index.* local.sh > $DIR/sha512.sums; cat $DIR/sha512.sums
      - name: Generate Attestations for Build Provenance v4
        id: generate_attestation
        uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
        with:
          subject-checksums: '${{env.DIR}}/sha512.sums'
          github-token: '${{github.token}}'
          create-storage-record: false
      - name: Fetch Attestation ID via Output
        env:
          URL: ${{steps.generate_attestation.outputs.attestation-url}}
        run: |
          pushd ${{env.DIR}} > /dev/null
            echo 1. ${{steps.generate_attestation.outputs.bundle-path}} > Runner_output.log
            echo 2. ${{env.URL}} >> Runner_output.log
            cat Runner_output.log; popd > /dev/null; cp -f index/index.state ${{env.DIR}}/index.state
      - name: Download Attestation (json) via API
        env:
          URL: ${{steps.generate_attestation.outputs.attestation-url}}
        run: |
          curl -s -L -o ${{env.DIR}}/Build_attestation.json \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{github.token}}" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            ${{env.URL}}/download
      - name: Draft Release via API
        id: draft_release
        env:
          TAG: ${{steps.git_fetch.outputs.TAG}}
        run: |
          export -- DRAFT=$(curl -s -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{github.token}}" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            https://api.github.com/repos/${{github.repository}}/releases \
            -d '{
              "tag_name":"${{env.TAG}}",
              "target_commitish":"main",
              "name":"${{env.TAG}}",
              "draft":true,
              "prerelease":false,
              "generate_release_notes":true,
              "make_latest":"false" 
            }' || exit 1) || exit 1
          responded_id=$(echo $DRAFT | jq .id)
          responded_body=$(echo $DRAFT | jq -r .body)
          echo "responded=$responded_id" >> $GITHUB_OUTPUT
          echo "response=$responded_body" >> $GITHUB_OUTPUT
      - name: Add Assets to Draft
        id: add_assets
        env:
          GH_TOKEN: ${{github.token}}
          TAG: ${{steps.git_fetch.outputs.TAG}}
        run: |
          gh release upload ${{env.TAG}} \
            ${{env.DIR}}/index.state#Index\ State\ \(statefile\) \
            ${{env.DIR}}/sha512.sums#Shasums\ \(sha512\) \
            ${{env.DIR}}/Runner_output.log#Runner\ Output\ \(log\) \
            ${{env.DIR}}/Build_attestation.json#Build\ Attestation\ \(json\) || exit 1
          echo SUMS=$(ls ${{env.DIR}}/ | sed -z 's/\n/\\ /g') >> $GITHUB_OUTPUT
          echo SIGNER=${{github.workflow_sha}} >> $GITHUB_OUTPUT
      - name: Publish Release via API
        env:
          TAG: ${{steps.git_fetch.outputs.TAG}}
          URL: ${{steps.generate_attestation.outputs.attestation-url}}
        run: |
          PUBLISH=$(curl -s -L -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{github.token}}" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            https://api.github.com/repos/${{github.repository}}/releases/${{steps.draft_release.outputs.responded}} \
            -d '{
              "name":"${{env.TAG}}",
              "body":"## Attestable - Immutable - Post Quantum\n> #### Attestation Created - ${{env.TAG}} Immutable Tag\n> - [${{env.URL}}](${{env.URL}})\n\n${{steps.draft_release.outputs.response}}\n\nBy: @0mniteck\n",
              "draft":false,
              "make_latest":"true"
            }') || exit 1
          if [[ "$PUBLISH" == *null* ]]; then exit 1; fi;
