name: 'Build Jekyll for GitHub Pages'
run-name: 'Jekyll Workflow'
description: 'A simple GitHub Workflow for producing Jekyll build artifacts compatible with GitHub Pages'
on:
  workflow_call:
    inputs:
      source:
        description: 'Directory where the source files reside.'
        required: false
        default: ./
        type: string
      destination:
        description: 'Output directory of the build. Although it can be nested inside the source, it cannot be the same as the source directory.'
        required: true
        default: ./_site
        type: string
      future:
        description: 'Publishes posts with a future date. When set to true, the build is made with the --future option which overrides the future option that may be set in a Jekyll configuration file.'
        required: false
        default: false
        type: boolean
      build_revision:
        description: 'The SHA-1 of the git commit for which the build is running. Default to GITHUB_SHA.'
        required: false
        default: ${{github.sha}}
        type: string
      verbose:
        description: 'Verbose output'
        required: false
        default: false
        type: boolean
      token:
        description: 'GitHub token'
        required: true
        default: ${{github.token}}
        type: string
jobs:
  job_id:
    runs-on: ubuntu-latest
    environment: 
      name: release
    steps:
      - name: docker
        uses: docker://ghcr.io/actions/jekyll-build-pages:6791ebfd912185ed59bfb5fb102664fa872496b79f87ff8b9cfba292a7345041 #v1.0.13
        with:
          source: ${{inputs.source}}
          destination: ${{inputs.destination}}
          verbose: ${{inputs.verbose}}
          token: ${{inputs.token}}
