name: Release
run-name: Release
description: GitHub Action to manage the immutable/attestable release cycle of 0mniteck/.pki
on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - Global_Fetch
  schedule:
    - cron: '0 0/6 * * *'
  push:
    paths:
      - 'registry/**'
      - 'index.**'
permissions: {}
concurrency:
  group: release-main
  cancel-in-progress: true
jobs:
  fetch-pki:
    name: Fetch PKI
    permissions:
      id-token: write
      contents: write
    concurrency:
      group: release
    secrets:
      DOCKER: ${{secrets.DOCKER}}
    uses: 0mniteck/.pki/.github/workflows/fetch.yml@5f4357453413b33d9c85d4152e48c45587ff28b4 # v0.0.247
  release-pki:
    name: Release PKI
    permissions:
      id-token: write
      contents: write
      attestations: write
    concurrency:
      group: release
    needs: fetch-pki
    uses: 0mniteck/.pki/.github/workflows/immutable.yml@e3286723846c55a223f6437ef9a078bbc14aac5a # v0.0.247
  attested-rel:
    name: Attest PKI
    permissions:
      id-token: write
      contents: read
      attestations: read
    concurrency:
      group: release
    environment:
      name: release
    needs: release-pki
    runs-on: ubuntu-latest
    steps:
      - name: Checkout v6
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Git Fetch
        run: git fetch && git pull origin main && echo Fetched
      - name: Run gh attestation verify
        env:
          GH_TOKEN: ${{github.token}}
        run: |
          for I in .github/{actions/jekyll,workflows}/* registry/* index.* local.sh ; do
            gh attestation verify $I --repo 0mniteck/.pki --source-ref refs/heads/main \
            --signer-workflow 0mniteck/.pki/.github/workflows/immutable.yml --digest-alg sha512 || exit 1;
            echo "$I Attested"; done; echo DONE;
  read-me:
    name: Publish readme.md
    permissions:
      id-token: write
      contents: write
    concurrency:
      group: release
    needs:
      - attested-rel
      - release-pki
    with:
      attested_url: ${{needs.release-pki.outputs.URL}}
    uses: 0mniteck/.pki/.github/workflows/read-me.yml@3a5852a387bb7f54af336f50acece56a001cf6c0 # v0.0.247
  gh-pages:
    name: Release Github Pages
    permissions: 
      id-token: write
      pages: write
      contents: read
    concurrency:
      group: release
    needs: read-me
    uses: 0mniteck/.pki/.github/workflows/gh-pages.yml@7d265b0ba9324017b4e315196a6483f3c59cffee # v0.0.247
