name: Release
run-name: Release
description: GitHub Action to manage the immutable/attestable release cycle of 0mniteck/.pki
on:
  workflow_dispatch:
    inputs:
      RUN_REF:
        required: true
        type: string
        description: 'State pinning to the immutable signers ref'
  repository_dispatch:
    types:
      - Global_Fetch
  watch:
    types:
      - started
  schedule:
    - cron: '0 0/6 * * *'
      timezone: America/Los_Angeles
  push:
    paths:
      - 'registry/*'
      - 'index/index.*'
permissions: {}
concurrency:
  group: release-main
  cancel-in-progress: true
jobs:
  fetch-pki:
    name: Fetch PKI
    permissions:
      id-token: write
      contents: write
    concurrency:
      group: release
    secrets:
      DOCKER: ${{secrets.DOCKER}}
    uses: 0mniteck/.pki/.github/workflows/fetch.yml@7e70a681b774f0f3cc7ba8989e621270bc54d12e # v0.0.247
  release-pki:
    name: Release PKI
    permissions:
      id-token: write
      contents: write
      attestations: write
    concurrency:
      group: release
    needs: fetch-pki
    uses: 0mniteck/.pki/.github/workflows/immutable.yml@4d101c99b0d87ec4e96e15661b6d383baf87e8c0 # v0.0.277
  attested-rel:
    name: Attest PKI
    permissions:
      id-token: write
      contents: read
      attestations: read
    concurrency:
      group: release
    environment:
      name: release
    needs: release-pki
    runs-on: ubuntu-latest
    steps:
      - name: Checkout v6
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Git Fetch
        id: git_fetch
        run: |
          git fetch && git pull origin main && echo Fetched
          echo "TAG=v0.0.$(cat index/index.version)" >> $GITHUB_OUTPUT
      - name: Run gh attestation verify
        env:
          GH_TOKEN: ${{github.token}}
          TAG: ${{steps.git_fetch.outputs.TAG}}
          SUMS: ${{needs.release-pki.outputs.SUMS}}
          SIGNER: ${{inputs.RUN_REF || 'cd57210d555d705f494bf9cfcc40c0d0c82462f1'}}
          SIGNER_WF: 0mniteck/.pki/.github/workflows/immutable.yml
        timeout-minutes: 10
        run: |
          for I in .github/{actions/jekyll,workflows}/* registry/* index/index.* local.sh ; do
            gh attestation verify $I --repo ${{github.repository}} --source-ref ${{github.ref}} \
              --signer-workflow ${{env.SIGNER_WF}} --digest-alg sha512 \
              --signer-digest ${{env.SIGNER}} --predicate-type provenance \
              --deny-self-hosted-runners -L 1 || exit 1;
            echo "$I Attested";
          done; echo Done checking provenance;
          
          gh release verify ${{env.TAG}} || exit 1; mkdir -p attestations/
          echo Done checking release by tag;
          gh release download ${{env.TAG}} -p '*.json' -p '*.log' -p '*.state' -p '*.sums' -D attestations
          
          for J in $(echo -en ${{env.SUMS}} | sed 's/\\//g'); do
            gh release verify-asset ${{env.TAG}} attestations/$J || exit 1;
            echo "$J Attested";  
          done; echo Done checking all attestations;
  read-me:
    name: Publish readme.md
    permissions:
      id-token: write
      contents: write
    concurrency:
      group: release
    needs:
      - attested-rel
      - release-pki
    with:
      attested_url: ${{needs.release-pki.outputs.URL}}
    uses: 0mniteck/.pki/.github/workflows/read-me.yml@5f5a3f361400226fbf6698a3fd94e4238f35bf72 # v0.0.247
  gh-pages:
    name: Release Github Pages
    permissions: 
      id-token: write
      pages: write
      contents: read
    concurrency:
      group: release
    needs: read-me
    uses: 0mniteck/.pki/.github/workflows/gh-pages.yml@7d265b0ba9324017b4e315196a6483f3c59cffee # v0.0.247
