name: Release
run-name: Release
description: GitHub Action to manage the immutable/attestable release cycle of 0mniteck/.pki
on:
  repository_dispatch:
    types:
      - Global_Fetch
  workflow_dispatch:   
  schedule:
    - cron: '0 0/6 * * *'
  push:
    paths:
      - 'registry/**'
      - 'index.**'
concurrency:
  group: release-main
  cancel-in-progress: true
permissions:
  id-token: write
  contents: write
  attestations: write
  artifact-metadata: write
jobs:
  fetch-pki:
    name: Fetch PKI
    concurrency:
      group: release
    uses: 0mniteck/.pki/.github/workflows/fetch.yml@d0a3bdd06c1884ecd67e4503482cb6214104aeba # v0.0.243
  release-pki:
    name: Release PKI
    concurrency:
      group: release
    needs: fetch-pki
    uses: 0mniteck/.pki/.github/workflows/immutable.yml@416d7eb821720e2cc602e3e63cfef745932f715a # v0.0.243
  attested-rel:
    name: Attest PKI
    runs-on: ubuntu-latest
    environment:
      name: release
    needs: release-pki
    permissions:
      id-token: write
      contents: read
      attestations: read
    concurrency:
      group: release
    steps:
      - name: Checkout v6
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Git fetch
        id: git_fetch
        run: git fetch && git pull origin main && echo Fetched
      - name: Run gh attestation verify
        env:
          GH_TOKEN: ${{github.token}}
        run: |
          for I in ${{github.workspace}}/.github/{actions/jekyll,workflows}/* ${{github.workspace}}/registry/* ${{github.workspace}}/index.* ${{github.workspace}}/local.sh ; do
            gh attestation verify $I --repo 0mniteck/.pki --source-ref refs/heads/main \
            --signer-workflow 0mniteck/.pki/.github/workflows/immutable.yml --digest-alg sha512 || exit 1;
            echo "$I Attested"; done; echo DONE;
  read-me:
    name: Publish Readme
    uses: 0mniteck/.pki/.github/workflows/read-me.yml@bcfc99236dd081e17cfc533233b8d66a371ecb88 # v0.0.221
    concurrency:
      group: release
    needs:
      - attested-rel
      - release-pki
    permissions:
      id-token: write
      contents: write
    with:
      attested_url: "${{needs.release-pki.outputs.URL}}"
  gh-pages:
    name: Release Github Pages
    uses: 0mniteck/.pki/.github/workflows/gh-pages.yml@57f212d011849aa3d2320c315df33a11dfff4a4c # v0.0.189
    concurrency:
      group: release
    needs: read-me
    permissions:
      contents: read
      pages: write
      id-token: write
