name: Sync Fork
run-name: Sync Fork
description: 'This workflow uses the GitHub CLI to keep one branch on a forked repo in sync with the upstream repo'
on:
  workflow_call:
permissions: {}
concurrency:
  group: release
  cancel-in-progress: true
jobs:
  sync:
    if: ${{github.ref != 'refs/heads/main'}}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      BRANCH_NAME: ${{github.ref_name}}
    steps:
      - name: Checkout v6
        with:
          ref: $BRANCH_NAME
          fetch-depth: 5
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Git Fetch
        run: git fetch && git pull origin ${{github.ref_name}} && echo Fetched
      - run: gh repo sync $REPOSITORY -b $BRANCH_NAME -s 0mniteck/.pki
        env:
          GITHUB_TOKEN: ${{github.token}}
          REPOSITORY: ${{github.repository}}
